bin:
  link: "~/.bin"

compton:
  link: "~"
  dependencies:
    - "compton"

dunst:
  link: "~/.config/dunst"
  dependencies:
    - "dunst"

# copy fonts and fonts.dir into ~/.fonts
fonts:
  link:
    - fonts.conf: "~/.config/fontconfig"
  postlink:
    - "git clone https://github.com/powerline/fonts ~/fonts/powerline-fonts"
    - ". ~/fonts/install.sh"
    - "sudo rm /usr/share/fonts/conf.d/70-no-bitmaps.conf"
    - "sudo ln -sv /usr/share/fontconfig/conf.avail/70-yes-bitmaps.conf /usr/share/fonts/conf.d"
    - "fc-cache -fv"
  dependencies:
    - "xset"
    - "mkfontdir"
    - "mkfontscale"

git:
  link: "~"

htop:
  link: "~/.config/htop"
  dependencies:
    - "htop"

i3:
  link:
    - config.ini: "~/.config/networkmanager-dmenu"
    - "*": "~/.config/i3"
    - ".*": "~/.config/i3"
  dependencies:
    - "i3"
    - "scrot"
    - "imagemagick"
    - "i3lock"
    - "rofi"
    - "acpi"
    - "sysstat"
    - "feh"
    - "jq"
    - "blueman"
    - "xbacklight"
    - "gnome-settings-daemon"
    - "network-manager"
    - "xclip"
  postlink:
    - "mkdir -p ~/.tmp"

mpd:
  link: "~/.config/mpd"
  postlink:
    - "mkdir -pv ~/.config/mpd/playlists"
    - "touch ~/.config/mpd/database"
  dependencies:
    - "mpd"
    - "mpc"

mpv:
  prelink:
    - "mkdir -p ~/Pictures/screenshots"
  link: "~/.config/mpv"
  dependencies:
    - "mpv"

ncmpcpp:
  link: "~/.ncmpcpp"
  dependencies:
    - "ncmpcpp"

other:
  link: "~/.config"
  dependencies:
    - "redshift"
    - "youtube-dl"
    - "p7zip"

polybar:
  link: "~/.config/polybar"
  dependencies:
    - "polybar"
    - "font-awesome-ttf"

ranger:
  link: "~/.config/ranger"
  dependencies:
    - "ranger"
    - "imagemagick"
    - "w3m"
    - "feh"
    - "atool"

rtorrent:
  link: "~"
  postlink:
    - "mkdir -pv ~/Downloads/complete ~/Downloads/incomplete ~/.rtorrent.sessions"
  dependencies:
    - "rtorrent"

system:
  link: "~"
  dependencies:
    - "rxvt-unicode"
    - "xrdb"

tmux:
  link: "~"
  dependencies:
    - "tmux"

# Install `system.devel` component
# sudo eopkg install -c system.devel
vim:
  link:
    - minisnip: "~/.vim"
    - "*": "~"
    - ".*": "~"
  postlink:
    - "sudo pip install jedi flake8 autopep8 pylint"
    - "sudo npm install -g eslint tern"
    - "cd ~/.vim/plugged/tern_for_vim && npm install"
  dependencies:
    - "vim"
    - "curl"
    - "ack"
    - "ctags"
    - "pip"
    - "llvm-clang"
    - "nodejs"
    - "pandoc"
    - "cppcheck"

weechat:
  link: "~/.weechat"
  dependencies:
    - "weechat"

zathura:
  link: "~/.config/zathura"
  dependencies:
    - "xdotool"
    - "poppler-devel"
    - "texlive-devel"
    - "girara-devel"
    - "texlive-all"
  postlink:
    - "mkdir -p ~/Documents/source"
    - "git clone https://github.com/pwmt/zathura ~/Documents/source/zathura"
    - "git clone https://github.com/pwmt/zathura-pdf-poppler ~/Documents/source/zathura-pdf-poppler"
    - "cd ~/Documents/source/zathura && sudo make install"
    - "cd ~/Documents/source/zathura-pdf-poppler && sudo make install"
