bin:
  link: "~/.bin"

compton:
  link: "~"
  dependencies:
    - "compton"

feh:
  link: "~/.config/feh"
  dependencies:
    - "feh"

fonts:
  link:
    - fonts.conf: "~/.config/fontconfig"
  postlink:
    - "git clone https://github.com/powerline/fonts ~/fonts/powerline-fonts"
    - "source ~/fonts/install.sh"
    - "sudo rm /usr/share/fonts/conf.d/70-no-bitmaps.conf"
    - "sudo ln -sv /usr/share/fontconfig/conf.avail/70-yes-bitmaps.conf /usr/share/fonts/conf.d"
    - "mkdir ~/.fonts"
    - "cp ./fonts/* ~/.fonts"
    - "cd ~/.fonts && mkfontdir"
    - "cd ~/.fonts && mkfontscale"
    - "fc-cache -fv"
  dependencies:
    - "xset"
    - "mkfontdir"
    - "mkfontscale"

git:
  link: "~"

htop:
  link: "~/.config/htop"
  dependencies:
    - "htop"

i3:
  link:
    - config.ini: "~/.config/networkmanager-dmenu"
    - "*": "~/.config/i3"
    - ".*": "~/.config/i3"
  dependencies:
    - "i3"
    - "scrot"
    - "slog"
    - "imagemagick"
    - "i3lock"
    - "rofi"
    - "acpi"
    - "sysstat"
    - "jq"
    - "blueman"
    - "xbacklight"
    - "gnome-settings-daemon"
    - "numix-gtk-theme"
    - "papirus-icon-theme"
    - "network-manager"
    - "xclip"
    - "xinput"
  postlink:
    - "mkdir -p ~/.tmp"

mpd:
  link: "~/.config/mpd"
  postlink:
    - "mkdir -pv ~/.config/mpd/playlists"
    - "touch ~/.config/mpd/database"
  dependencies:
    - "mpd"
    - "mpc"

mpv:
  link: "~/.config/mpv"
  postlink:
    - "mkdir -p ~/Pictures/Screenshots"
  dependencies:
    - "mpv"

ncmpcpp:
  link: "~/.ncmpcpp"
  dependencies:
    - "ncmpcpp"

other:
  link:
    - redshift.conf: "~/.vim"
  dependencies:
    - "redshift"
    - "youtube-dl"
    - "p7zip"
    - "cabextract"

polybar:
  link: "~/.config/polybar"
  dependencies:
    - "polybar"
    - "font-awesome-ttf"

ranger:
  link: "~/.config/ranger"
  dependencies:
    - "ranger"
    - "imagemagick"
    - "w3m"
    - "feh"
    - "atool"
    - "highlight"

rtorrent:
  link: "~"
  postlink:
    - "mkdir -pv ~/Downloads/complete ~/Downloads/incomplete ~/.rtorrent.sessions"
  dependencies:
    - "rtorrent"

system:
  link: "~"
  dependencies:
    - "rxvt-unicode"
    - "xrdb"

tmux:
  link: "~"
  dependencies:
    - "tmux"

# Install `system.devel` component
# sudo eopkg install -c system.devel
vim:
  link:
    - minisnip: "~/.vim"
    - after: "~/.vim"
    - "*": "~"
    - ".*": "~"
  postlink:
    - "curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    - "vim -c PlugInstall -c q! -c q!"
    - "curl -sL https://raw.githubusercontent.com/creationix/nvm/master/install.sh -o install_nvm.sh"
    - "chmod 775 install_nvm.sh"
    - "./install_nvm.sh"
    - "rm install_nvm.sh"
    - "sudo pip install jedi flake8 autopep8 pylint"
    - "sudo npm install -g eslint tern"
    - "cd ~/.vim/plugged/tern_for_vim && npm install"
    - "curl https://sh.rustup.rs -sSf | sh"
    - "rustup install nightly"
    - "rustup default nightly"
    - "rustup component add rust-src"
    - "rustup component add rustfmt"
    - "rustup component add clippy"
    - "cargo install racer"
  dependencies:
    - "vim"
    - "curl"
    - "ag"
    - "ctags"
    - "pip"
    - "llvm-clang"
    - "nodejs"
    - "pandoc"
    - "cppcheck"

weechat:
  link: "~/.weechat"
  dependencies:
    - "weechat"

dunst:
  prelink:
    - "./bin/compile-color-template ./dunst/dunstrc.template ./dunst/dunstrc"
  link:
    - dunstrc: "~/.config/dunst"
  dependencies:
    - "dunst"

  prelink:
    - "./bin/compile-color-template ./dunst/dunstrc.template ./dunst/dunstrc"
  link:
    - dunstrc: "~/.config/dunst"
  dependencies:
    - "dunst"

zathura:
  prelink:
    - "./bin/compile-color-template ./zathura/zathurarc.template ./zathura/zathurarc"
  link:
    - zathurarc: "~/.config/zathura"
  dependencies:
    - "xdotool"
    - "zathura"
    - "texlive-all"
