bin:
  link: "~/.bin"
compton:
  link: "~"
  dependencies:
    - "compton"
dunst:
  link: "~/.config/dunst"
  dependencies:
    - "dunst"
fonts:
  link:
    - fonts.conf: "~/.config/fontconfig"
    - "*": "~/.fonts"
    - ".*": "~/.fonts"
  postlink:
    - "git clone https://github.com/powerline/fonts ~/fonts/powerline-fonts"
    - ". ~/fonts/install.sh"
git:
  link: "~"
htop:
  link: "~/.config/htop"
  dependencies:
    - "htop"
i3:
  link: "~/.config/i3"
  dependencies:
    - "i3"
    - "scrot"
    - "imagemagick"
    - "i3lock"
    - "rofi"
    - "acpi"
    - "sysstat"
    - "feh"
    - "jq"
    - "blueman"
    - "xbacklight"
    - "gnome-settings-daemon"
    - "network-manager"
    - "xclip"
  postlink:
    - "mkdir -p ~/.tmp"
mpd:
  link: "~/.config/mpd"
  postlink:
    - "mkdir -pv ~/.config/mpd/playlists"
    - "touch ~/.config/mpd/database"
  dependencies:
    - "mpd"
    - "mpc"
mpv:
  prelink:
    - "mkdir -p ~/Pictures/screenshots"
  link: "~/.config/mpv"
  dependencies:
    - "mpv"
ncmpcpp:
  link: "~/.ncmpcpp"
  dependencies:
    - "ncmpcpp"
other:
  link: "~/.config"
  dependencies:
    - "redshift"
    - "youtube-dl"
polybar:
  link: "~/.config/polybar"
  dependencies:
    - "polybar"
    - "font-awesome-ttf"
ranger:
  link: "~/.config/ranger"
  dependencies:
    - "ranger"
    - "imagemagick"
    - "w3m"
    - "feh"
rtorrent:
  link: "~"
  postlink:
    - "mkdir -pv ~/Downloads/complete ~/Downloads/incomplete ~/.rtorrent.sessions"
  dependencies:
    - "rtorrent"
system:
  link: "~"
  dependencies:
    - "rxvt-unicode"
    - "xrdb"
templates:
  link: "~/.templates"
tmux:
  link: "~"
  dependencies:
    - "tmux"
vim:
  link: "~"
  postlink:
    - "rm -rf ~/.vim"
    - "curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    - "vim -c PlugInstall -c q! -c q!"
    - "~/.vim/plugged/youcompleteme/install.py --clang-completer"
  dependencies:
    - "vim"
    - "cmake"
    - "make"
    - "curl"
    - "g++"
weechat:
  link: "~/.weechat"
  dependencies:
    - "weechat"
zathura:
  link: "~/.config/zathura"
  dependencies:
    - "zathura"
    - "xdotool"
