bin:
  link: "~/.bin"
  overwrite: False
compton:
  link: "~"
  dependencies:
    - "compton"
fontconfig:
  link: "~/.config/fontconfig"
git:
  link: "~"
htop:
  link: "~/.config/htop"
  dependencies:
    - "htop"
i3:
  link: "~/.config/i3"
  dependencies:
    - "scrot"
    - "imagemagick"
    - "i3lock"
    - "rofi"
    - "i3lock"
    - "fonts-font-awesome"
    - "acpi"
    - "sysstat"
    - "feh"
    - "jq"
    - "blueman"
    - "xautolock"
    - "xbacklight"
    - "gnome-settings-daemon"
    - "network-manager"
    - "xclip"
mpd:
  link: "~/.config/mpd"
  scripts:
    - "mkdir -pv ~/.config/mpd/playlists"
    - "touch ~/.config/mpd/database"
  dependencies:
    - "mpd"
    - "mpc"
mpv:
  link: "~/.config/mpv"
  dependencies:
    - "mpv"
ncmpcpp:
  link: "~/.ncmpcpp"
  dependencies:
    - "ncmpcpp"
other:
  prelink:
    - "sudo add-apt-repository ppa:nilarimogard/webupd8"
    - "sudo apt-get update"
  link:
    - redshift.conf: "~/.config"
    - "*": "~/dotfiles"
    - ".*": "~/dotfiles"
  dependencies:
    - "redshift"
    - "redshift-gtk"
    - "nautilus"
    - "chromium-browser"
    - "youtube-dl"
qpdfview:
  link: "~/.config/qpdfview"
  dependencies:
    - "qpdfview"
ranger:
  link: "~/.config/ranger"
  dependencies:
    - "ranger"
    - "imagemagick"
    - "w3m"
    - "feh"
    - "atool"
rtorrent:
  link: "~"
  postlink:
    - "mkdir -pv ~/Downloads/complete ~/Downloads/incomplete ~/.rtorrent.sessions"
sublime-text-3/Packages/User:
  prelink:
    - "sudo add-apt-repository ppa:webupd8team/sublime-text-3"
    - "sudo apt-get update"
  link: "~/.config/sublime-text-3/Packages/User"
system:
  link: "~"
  postlink:
    - "xrdb ~/.Xresources"
    - "git clone https://github.com/powerline/fonts ~/fonts"
    - ". ~/fonts/install.sh"
  dependencies:
    - "rxvt-unicode-256color"
templates:
  link: "~/.templates"
tmux:
  link: "~"
  dependencies:
    - "tmux"
vim:
  link: "~"
  postlink:
    - "rm -rf ~/.vim"
    - "curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    - "vim -c PlugInstall -c q! -c q!"
    - "~/.vim/plugged/youcompleteme/install.py --clang-completer"
  dependencies:
    - "vim-gnome"
    - "build-essential"
    - "cmake"
    - "python-dev"
    - "python3-dev"
    - "curl"
weechat:
  link: "~/.weechat"
  dependencies:
    - "weechat"
